#!/bin/bash

set -e

# Install python alias
if [ $(which python3) ]; then
    if [ ! $(update-alternatives --list python | grep python3) ]; then
        update-alternatives --install /usr/bin/python python /usr/bin/python3 50
    fi
fi


mkdir -p /etc/dconf/db/local.d/
mkdir -p /etc/skel/.config/dconf/
cp -r /usr/lib/denios-skel/etc/dconf/db/local.d/denios-skel /etc/dconf/db/local.d/denios-skel

dconf compile /etc/dconf/db/local /etc/dconf/db/local.d/
dconf compile /etc/skel/.config/dconf/user /etc/dconf/db/local.d/

rsync -a --delete /usr/lib/denios-skel/etc/skel/ /etc/skel/
rsync -a /etc/skel/ /root/

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "5.0.16"; then
	echo "
" > /etc/apt/sources.list.d/denios.list
    cat /etc/apt/sources.list > /etc/apt/sources.list.old || true
    echo "
" > /etc/apt/sources.list
fi
